console.log("+----------------------------------------+")
console.log("|                                        |")
console.log("|    ❀ꗥ～ꗥ❀ 𝐀𝐁𝐂 𝐏𝐔𝐁𝐋𝐈𝐂 𝐒𝐂𝐇𝐎𝐎𝐋 ❀ꗥ～ꗥ❀     |")
console.log("|               New Delhi                |")
console.log("|     Academic Session - 2021-2022       |")
console.log("|              𝐑𝐄𝐏𝐎𝐑𝐓 𝐂𝐀𝐑𝐃               |")
console.log("|                                        |")
var name = "| Name     →    Shravan                  |"
console.log(name)
var grade = "| Std.     →    12th [A]                 |"
console.log(grade)
var rollno = "| Roll No  →    37                       |"
console.log(rollno)
console.log("|                                        |")
console.log("|----------------------------------------|")
console.log("|  S.no    Subject       Marks     Grade |")
console.log("|----------------------------------------|")
console.log("|  1.      English          91       A2  |")
console.log("|----------------------------------------|")
console.log("|  2.      Mathematics      92       A2  |")
console.log("|----------------------------------------|")
console.log("|  3.      Physics          90       A2  |")
console.log("|----------------------------------------|")
console.log("|  4.      Chemistry        88       A2  |")
console.log("|-------------------+------------+-------|")
console.log("|       𝗥𝗘𝗦𝗨𝗟𝗧      |      Total |   361 |")
console.log("|                   +------------+-------|")
console.log("|   ⚛ 🎀 𝗣𝗔𝗦𝗦 🎀 ⚛  | Percentage | 90.25 |")
console.log("+-------------------+------------+-------+")
